databases:
  - name: beauty-kabylova-db
    plan: free
    databaseName: beauty_kabylova
    user: beauty_kabylova

services:
  - type: web
    name: beauty-kabylova
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DATABASE_URL
        fromDatabase:
          name: beauty-kabylova-db
          property: connectionString
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        sync: false
