# Generated by Django 4.2.30 on 2026-06-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(default='г. Астана, ул. Байтурсынова 17/1', max_length=200)),
                ('working_hours', models.CharField(default='Круглосуточно', max_length=100)),
                ('promo_text', models.CharField(default='-10% на первый чек от 10 000 тг', max_length=300)),
                ('instagram_url', models.URLField(default='https://www.instagram.com/by_kabylova')),
                ('hero_image', models.ImageField(blank=True, upload_to='hero/')),
                ('about_image', models.ImageField(blank=True, upload_to='about/')),
                ('bio', models.TextField(blank=True, default='')),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('clients_count', models.PositiveIntegerField(default=0)),
                ('works_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
