# Generated by Django 5.2.15 on 2026-06-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email для связи'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(blank=True, default='Все права защищены', max_length=300, verbose_name='Текст в футере'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_text',
            field=models.CharField(default='by Kabylova', max_length=100, verbose_name='Текст логотипа'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Beauty by Kabylova', max_length=200, verbose_name='Название сайта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram (@username или ссылка)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vk_url',
            field=models.URLField(blank=True, verbose_name='VK'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30, verbose_name='WhatsApp (номер)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, upload_to='about/', verbose_name='Фото о мастере'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio / Описание'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='clients_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Клиентов'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='hero/', verbose_name='Фото героя'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='promo_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Текст акции'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='working_hours',
            field=models.CharField(blank=True, max_length=100, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='works_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Работ'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='years_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Лет опыта'),
        ),
    ]
