# Generated by Django 5.2.15 on 2026-06-25 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('specialization', models.CharField(blank=True, max_length=300, verbose_name='Специализация')),
                ('photo', models.ImageField(blank=True, upload_to='masters/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.master', verbose_name='Мастер'),
        ),
        migrations.AddField(
            model_name='service',
            name='masters',
            field=models.ManyToManyField(blank=True, related_name='services', to='booking.master', verbose_name='Мастера'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='booking.master', verbose_name='Мастер'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('date', 'time', 'master')},
        ),
    ]
