# Generated by Django 4.2.30 on 2026-06-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('alt_text', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('manicure', 'Маникюр'), ('pedicure', 'Педикюр'), ('design', 'Дизайн')], max_length=20)),
                ('instagram_post_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
